spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debounce_proto
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 2000

server:
  port: 8080

logging:
  level:
    com.example.cachedebouncing: DEBUG
